cake/urls.py
from django.urls import path 
from . import views


app_name = 'cake'


urlpatterns = [
path('', views.home, name='home'),
path('list', views.product_list, name='product_list'),
path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
path('contact', views.contact, name='contact'),
path('about', views.about, name='about'),
path('bosspage', views.adminpage, name='adminpage'),
path('bosspage01', views.adminpage01, name='adminpage01'),
path('bosspage2', views.adminpage2, name='adminpage2'),

]

cakestore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('cake.urls', namespace='cake')),

]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path 
from . import views

app_name = 'orders'

urlpatterns = [
path('create/', views.order_create, name='order_create'),
]

orders/models.py
from django.db import models 
from cake.models import Product
# Create your models here.

class Order(models.Model):
	first_name = models.CharField(max_length=50) 
	last_name = models.CharField(max_length=50) 
	email = models.EmailField()
	address = models.CharField(max_length=250) 
	created = models.DateTimeField(auto_now_add=True) 
	updated = models.DateTimeField(auto_now=True) 
	paid = models.BooleanField(default=False)



	class Meta:
		ordering = ('-created',)
	def __str__(self):
		return f'Order {self.id}'
	def get_total_cost(self):
		return sum(item.get_cost() for item in self.items.all())



class OrderItem(models.Model):
	order = models.ForeignKey(Order,related_name='items',on_delete=models.CASCADE) 
	product = models.ForeignKey(Product,related_name='order_items',on_delete=models.CASCADE)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	quantity = models.PositiveIntegerField(default=1)
	def __str__(self): 
		return str(self.id)
	def get_cost(self):
		return self.price * self.quantity

orders/forms.py
from django import forms 
from .models import Order


class OrderCreateForm(forms.ModelForm): 
	class Meta:
		model = Order
		fields = ['first_name', 'last_name', 'email', 'address']

orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm 
from cart.cart import Cart
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def order_create(request):
	cart = Cart(request)
	if request.method == 'POST':
		form = OrderCreateForm(request.POST) 
		if form.is_valid():
			order = form.save() 
			for item in cart:
				OrderItem.objects.create(order=order, product=item['product'],price=item['price'], quantity=item['quantity'])
	# clear the cart 
			cart.clear()
			return render(request,'orders/created.html', {'order': order})
	else:
		form = OrderCreateForm()
	return render(request, 'orders/create.html',{'cart': cart, 'form': form})

orders/templates/orders/checkout.html
{% extends "index.html" %}
   {% load static %}
{% block title %}
<title>Checkout</title>
{% endblock %}
{% block content %}

    <!-- Breadcrumb Begin -->
    <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="breadcrumb__text">
                        <h2>Checkout</h2>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="breadcrumb__links">
                        <a href="./index.html">Home</a>
                        <span>Checkout</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Checkout Section Begin -->
    <section class="checkout spad">
        <div class="container">
            <div class="checkout__form">
                <form method="post" class="order-form">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-8 col-md-6">
                            <h6 class="checkout__title">Billing Details</h6>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>Fist Name<span>*</span></p>
                                        <input type="text" name="first_name" maxlength="50" required="" id="id_first_name">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>Last Name<span>*</span></p>
                                        <input type="text" name="last_name" maxlength="50" required="" id="id_last_name">
                                    </div>
                                </div>
                            </div>
                            
                            <div class="checkout__input">
                                <p>Address<span>*</span></p>
                                <input type="text" name="address" maxlength="250" required="" id="id_address">
                                
                            </div>
                            
                            <div class="row">
                               
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>Email<span>*</span></p>
                                        <input type="email" name="email" maxlength="254" required="" id="id_email">
                                    </div>
                                </div>
                            </div>
                            
                            
                        </div>
                        
                        <div class="col-lg-4 col-md-6">
                            <div class="checkout__order">
                                <h6 class="order__title">Your order</h6>
                                <div class="checkout__order__products">Product <span>Total</span></div>
                                {% for item in cart %}
                                {% with product=item.product %}
                                <ul class="checkout__total__products">
                                    <li>{{product.name }} <span>$ {{ item.price }}</span></li>
                                </ul>
                                {% endwith %}
                                    {% endfor %}
                                <ul class="checkout__total__all">
                                    <li>Subtotal <span>${{ cart.get_total_price }}</span></li>
                                    <li>Total <span>${{ cart.get_total_price }}</span></li>
                                </ul>
                                
                                <button type="submit" class="site-btn">PLACE ORDER</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
    <!-- Checkout Section End -->

   {% endblock %}

orders/templates/orders/create.html
{% extends "index.html" %}
   {% load static %}
{% block title %}
<title>Checkout</title>
{% endblock %}
{% block content %}

    <!-- Breadcrumb Begin -->
    <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="breadcrumb__text">
                        <h2>Checkout</h2>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="breadcrumb__links">
                        <a href="./index.html">Home</a>
                        <span>Checkout</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Checkout Section Begin -->
    <section class="checkout spad">
        <div class="container">
            <div class="checkout__form">
                <form method="post" class="order-form">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-8 col-md-6">
                            <h6 class="checkout__title">Billing Details</h6>
                            <div class="row">
                              {% if request.user.is_authenticated %}
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>First Name<span>*</span></p>
                                        <input type="text" name="first_name" maxlength="50" required="" value="{{ request.user.first_name }}" id="id_first_name">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>Last Name<span>*</span></p>
                                        <input type="text" name="last_name" maxlength="50" required="" value="{{ request.user.last_name }}" id="id_last_name">
                                    </div>
                                </div>
                            </div>
                            
                            <div class="checkout__input">
                                <p>Address<span>*</span></p>
                                <input type="text" name="address" maxlength="250" required="" id="id_address">
                                
                            </div>
                            
                            <div class="row">
                               
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p>Email<span>*</span></p>
                                        <input type="email" name="email" maxlength="254" required="" value="{{ request.user.email }}" id="id_email">
                                    </div>
                                </div>
                            </div>
                            
                          {% endif %}  
                        </div>
                        
                        <div class="col-lg-4 col-md-6">
                            <div class="checkout__order">
                                <h6 class="order__title">Your order</h6>
                                <div class="checkout__order__products">Product <span>Total</span></div>
                                {% for item in cart %}
                                {% with product=item.product %}
                                <ul class="checkout__total__products">
                                    <li>{{product.name }} <span>$ {{ item.price }}</span></li>
                                </ul>
                                {% endwith %}
                                    {% endfor %}
                                <ul class="checkout__total__all">
                                    <li>Subtotal <span>${{ cart.get_total_price }}</span></li>
                                    <li>Total <span>${{ cart.get_total_price }}</span></li>
                                </ul>
                                
                                <button type="submit" class="site-btn">PLACE ORDER</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
    <!-- Checkout Section End -->

   {% endblock %}

orders/templates/orders/created.html
{% block title %}
     Thank you
   {% endblock %}
{% block content %}
<h1>Thank you</h1>
<p>Your order has been successfully completed. Your order number is <strong>{{ order.id }}</strong>.</p>
   {% endblock %}
 