cake/urls.py
from django.urls import path 
from . import views


app_name = 'cake'


urlpatterns = [
path('', views.home, name='home'),
path('list', views.product_list, name='product_list'),
path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
path('contact', views.contact, name='contact'),
path('about', views.about, name='about'),
path('bosspage', views.adminpage, name='adminpage'),
path('bosspage01', views.adminpage01, name='adminpage01'),
path('bosspage2', views.adminpage2, name='adminpage2'),

]

cakestore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('cake.urls', namespace='cake')),

]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path 
from . import views


app_name = 'cart'




urlpatterns = [
path('', views.cart_detail, name='cart_detail'), 
path('add/<int:product_id>/', views.cart_add, name='cart_add'), 
path('remove/<int:product_id>/', views.cart_remove,name='cart_remove'),
]

cake/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
	name = models.CharField(max_length=200,db_index=True) 
	slug = models.SlugField(max_length=200,unique=True)
	class Meta:
		ordering = ('name',)
		verbose_name = 'category' 
		verbose_name_plural = 'categories'
	def __str__(self): 
		return self.name

	def get_absolute_url(self):
		return reverse('cake:product_list_by_category',args=[self.slug])




class Product(models.Model):
	category = models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE) 
	name = models.CharField(max_length=200, db_index=True) 
	slug = models.SlugField(max_length=200, db_index=True)
	image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
	description = models.TextField(blank=True)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	available = models.BooleanField(default=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	class Meta:
		ordering = ('name',) 
		index_together = (('id', 'slug'),)
	def __str__(self): 
		return self.name

	def get_absolute_url(self):
		return reverse('cake:product_detail',args=[self.id, self.slug])

	def get_image(self):
		if self.image and hasattr(self.image, 'url'):
			return self.image.url
		else:
			return "https://i.dlpng.com/static/png/5592534-pin-by-kim-reed-on-sewing-happy-birthday-cake-png-transparent-happy-birthday-cake-png-840_671_preview.png"









class ProductImage(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    images = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    images1 = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    images2 = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    images3 = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)


    def get_photo1(self):
    	if self.images and hasattr(self.images, 'url'):
    		return self.images.url
    	else:
    		return "https://i.dlpng.com/static/png/5592534-pin-by-kim-reed-on-sewing-happy-birthday-cake-png-transparent-happy-birthday-cake-png-840_671_preview.png"

    def get_photo2(self):
    	if self.images1 and hasattr(self.iimages1, 'url'):
    		return self.images1.url
    	else:
    		return "https://i.dlpng.com/static/png/5592534-pin-by-kim-reed-on-sewing-happy-birthday-cake-png-transparent-happy-birthday-cake-png-840_671_preview.png"

    def get_photo3(self):
    	if self.images2 and hasattr(self.images2, 'url'):
    		return self.images2.url
    	else:
    		return "https://i.dlpng.com/static/png/5592534-pin-by-kim-reed-on-sewing-happy-birthday-cake-png-transparent-happy-birthday-cake-png-840_671_preview.png"

    def get_photo4(self):
    	if self.images3 and hasattr(self.images3, 'url'):
    		return self.images3.url
    	else:
    		return "https://i.dlpng.com/static/png/5592534-pin-by-kim-reed-on-sewing-happy-birthday-cake-png-transparent-happy-birthday-cake-png-840_671_preview.png"


class Contact(models.Model):
	name = models.CharField(max_length=100, db_index=True) 
	email = models.EmailField()
	body = models.TextField()

cake/forms.py
from django import forms 
from .models import *
class ContactCreateForm(forms.ModelForm): 
	class Meta:
		model = Contact
		fields = ['name','email','body']

class Adminmage(forms.ModelForm): 
	class Meta:
		model = ProductImage
		fields = ['product','images','images1','images2','images3']

class Adminpage(forms.ModelForm): 
	class Meta:
		model = Category
		fields = ['name','slug']

	class Meta:
		model = Product
		fields = ['category','name','slug','image','description','price','available']
	

cake/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Product,ProductImage,Contact
from .forms import ContactCreateForm,Adminpage,Adminmage
from cart.forms import CartAddProductForm
from django.forms import modelformset_factory
def home(request, category_slug=None):
	category = None
	categories = Category.objects.all()
	products = Product.objects.filter(available=True)
 
	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		products = products.filter(category=category) 
	return render(request, 'index.html',{'category': category,'categories': categories, 'products': products})



def product_list(request, category_slug=None): 
	category = None
	categories = Category.objects.all()
	products = Product.objects.filter(available=True) 
	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		products = products.filter(category=category) 
	return render(request,'product/list.html', {'category': category,'categories': categories, 'products': products})



def product_detail(request, id, slug): 
	product = get_object_or_404(Product,id=id, slug=slug, available=True)
	images = ProductImage.objects.filter(product=product)
	cart_product_form = CartAddProductForm()
	return render(request, 'product/detail.html',{'product': product,'cart_product_form': cart_product_form,'images':images})	

def contact(request):
	if request.method == 'POST':
		form = ContactCreateForm(data=request.POST)
		if form.is_valid():
			form.save()
	else:
		form = ContactCreateForm()
	return render(request,'contact.html',{'form':form})

def about(request):
	return render(request,'about.html',{})


def adminpage(request):
	if request.method == 'POST':
		form = Adminpage(data=request.POST)
		if form.is_valid():
			form.save()
			return render(request,'adminpage01.html',{})
	else:
		form = Adminpage()

	return render(request,'adminpage.html',{'form':form})

def adminpage01(request):
	return render(request,'adminpage01.html',{})


def adminpage2(request):
	if request.method == 'POST':
		form = Adminmage(data=request.POST)
		if form.is_valid():
			form.save()
			return render(request,'adminpage01.html',{})
	else:
		form = Adminmage()

	return render(request,'adminpage2.html',{'adminmage':form})

cake/templates/about.html
{% extends "index.html" %}
   {% load static %}
{% block title %}
<title>About</title>
{% endblock %}
{% block content %}

    <!-- Breadcrumb Begin -->
    <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="breadcrumb__text">
                        <h2>About</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- About Section Begin -->
    <section class="about spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <img style="width:100%; height:500px;" src="{% static 'img/about1.png' %}">
                </div>
            </div>
            <br>
<br>
<br>
<br>
            <div class="row">
                <div class="col-lg-6 col-md-6">
                    <div class="about__text">
                        <div class="section-title">
                            <span>About Sylvia pastries</span>
                            <h2>Cakes and bakes from the one that does it Best!</h2>
                        </div>
                        <p>Sylvia pastries offers a variety of pastries with unrivalled taste and sevrved with the epitome of style and even dear i say Swag we do a good job of Providing you with the best pastries that are very afforable and easily acessable to you and your friends</p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                     <img src="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/bea51f9b-197f-474c-9077-9b51270c2f1b/dapqdl0-66f6989c-4cf5-4a01-ad04-b26e381639e8.png/v1/fill/w_1024,h_1032,q_80,strp/mystery_chibi_cupcake_adopts__open__by_tigress1051_dapqdl0-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3siaGVpZ2h0IjoiPD0xMDMyIiwicGF0aCI6IlwvZlwvYmVhNTFmOWItMTk3Zi00NzRjLTkwNzctOWI1MTI3MGMyZjFiXC9kYXBxZGwwLTY2ZjY5ODljLTRjZjUtNGEwMS1hZDA0LWIyNmUzODE2MzllOC5wbmciLCJ3aWR0aCI6Ijw9MTAyNCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.5zelxJkrN1Vo6bXdj9bbNyc-tJdk95YcT0HU7BplUy4">
                </div>
            </div>
        </div>
    </section>
    <!-- About Section End -->
    
    <!-- Team Section Begin -->
    <section class="team spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 col-md-7 col-sm-7">
                    <div class="section-title">
                        <span>Our team</span>
                        <h2> The squad </h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="team__item set-bg" data-setbg="{% static 'img/kosi.png'%}">
                        <div class="team__item__text">
                            <h6>KOSI</h6>
                            <span>Baker</span>
                            <div class="team__item__social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                                <a href="#"><i class="fa fa-youtube-play"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="team__item set-bg" data-setbg="{% static 'img/muyiwa.png'%}">
                        <div class="team__item__text">
                            <h6>ALASHI</h6>
                            <span>WEB DEV</span>
                            <div class="team__item__social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                                <a href="#"><i class="fa fa-youtube-play"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Team Section End -->

{% endblock %}

cake/templates/adminpage.html
Add a product

<form method="POST">
	{% csrf_token %}
	{{form.as_p}}
	<button type="submit" class="site-btn">Submit</button>
</form>



Next---

cake/templates/adminpage01.html
add more pictures

<a href="{% url 'cake:adminpage2'%}">ADD</a>

cake/templates/adminpage2.html
Add a product

<form action="." method="POST">
	{% csrf_token %}
	{{adminmage.as_p}}
	<button type="submit" class="site-btn">Submit</button>

</form>



Next---

cake/templates/base.html
{% load static %}
   <!DOCTYPE html>
   <html>
<head>
<meta charset="utf-8" />
<title>{% block title %}My shop{% endblock %}</title> <link href="{% static "css/base.css" %}" rel="stylesheet">
     </head>
     <body>
<div id="header">
<a href="/" class="logo">My shop</a>
</div>
<div id="subheader">
<div class="cart">
{% with total_items=cart|length %} {% if total_items > 0 %}
Your cart:
<a href="{% url "cart:cart_detail" %}">
{{ total_items }} item{{ total_items|pluralize }},
${{ cart.get_total_price }} </a>
{% else %}
Your cart is empty.
       {% endif %}
     {% endwith %}
</div>
       </div>
<div id="content">
{% block content %} {% endblock %}
       </div>
     </body>
</html>

cake/templates/contact.html
{% extends "index.html" %}
   {% load static %}
{% block title %}
<title>Contact</title>
{% endblock %}
{% block content %}
    <!-- Contact Section Begin -->
    <section class="contact spad">
        <div class="container">
            <div class="map">
                <img style=" width:100%; height:470px;" src="https://marketingweek.imgix.net/content/uploads/2017/07/04160751/Compass_1240-2.jpg">
            </div>
<br>
<br>
            <div class="row">
                <div class="col-lg-4">
                    <div class="contact__text">
                        <h3>Contact With us</h3>
                        
                        
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="contact__form">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-6">
                                    <input placeholder="Name" type="text" name="name" maxlength="200" required="" id="id_name">
                                </div>
                                <div class="col-lg-6">
                                    <input placeholder="Email" type="email" name="email" maxlength="254" required="" id="id_email">
                                </div>
                                <div class="col-lg-12">
                                    <textarea placeholder="Message"  name="body" cols="40" rows="10" required="" id="id_body"></textarea>
                                    <button type="submit" class="site-btn">Send Us</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Contact Section End -->

{% endblock %}

cake/templates/index.html
<!DOCTYPE html>
<html lang="zxx">
{%load static %}
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Cake Template">
    <meta name="keywords" content="Cake, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}<title>Cake</title>{% endblock %}

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700;800;900&display=swap"
    rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&display=swap"
    rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/flaticon.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/barfiller.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css'%}" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Offcanvas Menu Begin -->
    <div class="offcanvas-menu-overlay"></div>
    <div class="offcanvas-menu-wrapper">
        <div class="offcanvas__cart">
            <div class="offcanvas__cart__links">
                <a href="#" class="search-switch"><img src="{% static 'img/icon/search.png' %}" alt=""></a>
                <a href="#"><img src="{% static 'img/icon/heart.png'%}" alt=""></a>
            </div>
            <div class="offcanvas__cart__item">
                <a href="#"><img src="{% static 'img/icon/cart.png'%}" alt=""> <span>0</span></a>
                <div class="cart__price">Cart: <span>$0.00</span></div>
            </div>
        </div>
        <div class="offcanvas__logo">
            <a href="{% url 'cake:home' %}"><img src="{% static 'img/sylvia-logo.png'%}" alt=""></a>
        </div>
        <div id="mobile-menu-wrap"></div>
        <div class="offcanvas__option">
            <ul>
              
                <li><a href="{% url 'account_login' %}">Sign in</a></li>
            </ul>
        </div>
    </div>
    <!-- Offcanvas Menu End -->

    <!-- Header Section Begin -->
    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="header__top__inner">
                            <div class="header__top__left">
                                <ul>{% if request.user.is_authenticated %}
                                    Hello {{ request.user.first_name }},
                                    {%else%}
                                    <li><a href="{% url 'account_login' %}">Sign in</a></li>
                                    }
                                {% endif %}
                                </ul>
                            </div>
                            <div class="header__logo">
                                <a href="{% url 'cake:home' %}"><img style="width:120px; height:52px;" src="{% static 'img/sy.png'%}" alt=""></a>
                            </div>
                            <div class="header__top__right">
                                <div class="header__top__right__links">
                                    <a href="#" class="search-switch"><img src="{% static 'img/icon/search.png'%}" alt=""></a>
                                    
                                </div>
                                {% with total_items=cart|length %} 
                                {% if total_items > 0 %}
                                <div class="header__top__right__cart">
                                    <a href="{% url 'cart:cart_detail' %}"><img src="{% static 'img/icon/cart.png'%}" alt=""> <span>
                                    {{ total_items }}</span></a>
                                    <div class="cart__price">Cart: <span>
                                    ${{ cart.get_total_price }}</span></div>
                                </div>
                                {% else %}
                                <div class="header__top__right__cart">
                                    <a href="{% url 'cart:cart_detail' %}"><img src="{% static 'img/icon/cart.png'%}" alt=""> <span>0</span></a>
                                    <div class="cart__price">Cart: <span>$0.00</span></div>
                                </div>
                                       {% endif %}
                                     {% endwith %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="canvas__open"><i class="fa fa-bars"></i></div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <nav class="header__menu mobile-menu">
                        <ul>
                            <li class="active"><a href="{% url 'cake:home' %}">Home</a></li>
                            <li><a href="{% url 'cake:product_list' %}">Shop</a></li>
                            <li><a href="{% url 'cake:about' %}">About</a></li>
                            <li><a href="{% url 'cake:contact' %}">Contact</a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- Header Section End -->
{% block content %}
    <!-- Hero Section Begin -->
    <section class="hero">
        <div class="hero__slider owl-carousel">
            <div class="hero__item set-bg" data-setbg="https://images.unsplash.com/photo-1574085733277-851d9d856a3a?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MjB8fHxlbnwwfHx8&w=1000&q=80">
                <div class="container">
                    <div class="row d-flex justify-content-center">
                        <div class="col-lg-8">
                            <div class="hero__text">
                                <h2>Making your life sweeter one bite at a time!</h2>
                                <a href="{% url 'cake:product_list' %}" class="primary-btn">Our cakes</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="hero__item set-bg" data-setbg="https://images.unsplash.com/photo-1574085733277-851d9d856a3a?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MjB8fHxlbnwwfHx8&w=1000&q=80">
                <div class="container">
                    <div class="row d-flex justify-content-center">
                        <div class="col-lg-8">
                            <div class="hero__text">
                                <h2>Making your life sweeter one bite at a time!</h2>
                                <a href="{% url 'cake:product_list' %}" class="primary-btn">Our cakes</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Hero Section End -->
<br>
<br>

    <!-- Categories Section Begin -->
    <div class="categories">
        <div class="container">
            <div class="row">
                <div class="categories__slider owl-carousel">
                    {% for c in categories %}
                    <div class="categories__item">
                        <a href="{{ c.get_absolute_url }}">
                        <div class="categories__item__icon">
                            <span class="flaticon-006-macarons"></span>
                            <h5>{{ c.name }} </h5>
                        </div>
                        </a>
                    </div>
                    {% endfor %}
                    {% for c in categories %}
                    <div class="categories__item">
                        <a href="{{ c.get_absolute_url }}">
                        <div class="categories__item__icon">
                            <span class="flaticon-006-macarons"></span>
                            <h5>{{ c.name }} </h5>
                        </div>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <!-- Categories Section End -->

    <!-- Product Section Begin -->
    <section class="product spad">
        
        <div class="container">
            <div class="row">
                {% for product in products %}
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="product__item">
                        <div class="product__item__pic set-bg" 
                        data-setbg="{{ product.get_image}}">
                            <div class="product__label">
                                <span>{{ product.category }}</span>
                            </div>
                        </div>
                        <div class="product__item__text">
                            <h6><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h6>
                            <div class="product__item__price">#{{ product.price }}</div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <!-- Product Section End -->

  
    
<br>
<br>
<br>
<br>

    
{% endblock %}
    <!-- Footer Section Begin -->
    <footer class="footer set-bg" data-setbg="{% static 'img/footer-bg.jpg'%}">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="footer__widget">
                        <h6>WORKING HOURS</h6>
                        <ul>
                            <li>Monday - Friday: 08:00 am – 08:30 pm</li>
                            <li>Saturday: 10:00 am – 16:30 pm</li>
                            
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="footer__about">
                        <div class="footer__logo">
                            <a href="#"><img src="{% static 'img/sy.png'%}" alt=""></a>
                        </div>
                        <p>Providing you with the best pastries that are very afforable and easily acessable to you and your friends</p>
                        <div class="footer__social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="footer__newslatter">
                        <h6>Subscribe</h6>
                        <p>Get latest updates and offers.</p>
                        <div class="footer__social">
                        <a href="#"><i class="fa fa-youtube-play"></i></a>
                        <a href="#"><i class="fa fa-youtube-play"></i></a>
                        <a href="#"><i class="fa fa-youtube-play"></i></a>
                        <a href="#"><i class="fa fa-youtube-play"></i></a>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer Section End -->

<!-- Search Begin -->
<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch">+</div>
        <form class="search-model-form">
            <input type="text" id="search-input" placeholder="Search here.....">
        </form>
    </div>
</div>
<!-- Search End -->

<!-- Js Plugins -->
<script src="{% static 'js/jquery-3.3.1.min.js'%}"></script>
<script src="{% static 'js/bootstrap.min.js'%}"></script>
<script src="{% static 'js/jquery.nice-select.min.js'%}"></script>
<script src="{% static 'js/jquery.barfiller.js'%}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
<script src="{% static 'js/jquery.slicknav.js'%}"></script>
<script src="{% static 'js/owl.carousel.min.js'%}"></script>
<script src="{% static 'js/jquery.nicescroll.min.js'%}"></script>
<script src="{% static 'js/main.js'%}"></script>
</body>

</html>