cake/urls.py
from django.urls import path 
from . import views


app_name = 'cake'


urlpatterns = [
path('', views.home, name='home'),
path('list', views.product_list, name='product_list'),
path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
path('contact', views.contact, name='contact'),
path('about', views.about, name='about'),
path('bosspage', views.adminpage, name='adminpage'),
path('bosspage01', views.adminpage01, name='adminpage01'),
path('bosspage2', views.adminpage2, name='adminpage2'),

]

cakestore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('cake.urls', namespace='cake')),

]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path 
from . import views


app_name = 'cart'




urlpatterns = [
path('', views.cart_detail, name='cart_detail'), 
path('add/<int:product_id>/', views.cart_add, name='cart_add'), 
path('remove/<int:product_id>/', views.cart_remove,name='cart_remove'),
]

orders/urls.py
from django.urls import path 
from . import views

app_name = 'orders'

urlpatterns = [
path('create/', views.order_create, name='order_create'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 6)]

class CartAddProductForm(forms.Form): 
	quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int) 
	override = forms.BooleanField(required=False,initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404 
from django.views.decorators.http import require_POST
from cake.models import Product
from .cart import Cart
from .forms import CartAddProductForm

# Create your views here.
@require_POST
def cart_add(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id) 
	form = CartAddProductForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data 
		cart.add(product=product,quantity=cd['quantity'],override_quantity=cd['override']) 
	return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id) 
	cart.remove(product)
	return redirect('cart:cart_detail')


def cart_detail(request):
	form = CartAddProductForm(initial={'override': True})
	cart = Cart(request)
	for item in cart:
		item['update_quantity_form'] = CartAddProductForm(initial={ 'quantity': item['quantity'],'override': True})
	return render(request, 'details.html', {'cart': cart, 'form':form})

cart/templates/details.html
{% extends "index.html" %}
   {% load static %}
{% block title %}
<title>Your shopping cart</title>
{% endblock %}
{% block content %}
    <!-- Breadcrumb Begin -->
    <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="breadcrumb__text">
                        <h2>Shopping cart</h2>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="breadcrumb__links">
                        <a href="./index.html">Home</a>
                        <span>Shopping cart</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Shopping Cart Section Begin -->
    <section class="shopping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="shopping__cart__table">
                        <table>
                            <thead>
                                <tr>
                                    <th>Product</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                    <th>Delete</th>
                                    
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in cart %}
                                {% with product=item.product %}

                                <tr>
                                    <td class="product__cart__item">
                                        <div class="product__cart__item__pic">
                                            <img style="width:90px; height:90px;" src="{{ product.image.url }}" alt="">
                                        </div>
                                        <div class="product__cart__item__text">
                                            <h6>{{product.name }}</h6>
                                            <h5>${{ item.price }}</h5>
                                        </div>
                                    </td>
                        <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                    <td class="quantity__item">
                                        <div class="quantity">
                                            {{ item.update_quantity_form.quantity }}
                                            </div>{% csrf_token %}
                                            {{ item.update_quantity_form.override }}
                                            <button style=" text-align: center; line-height: 38px; border-radius:50%;" type="submit" class="fa fa-spinner" ></button>
                                            
                                        </div>
                                      </div>
                                    </td>
                                    </form>
                                    <td class="cart__price">$ {{ item.total_price }}</td>
                                    <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                                    <td class="cart__close">
                                    <button class="icon_close" style="font-size: 18px;display: inline-block;color: #111111;height: 40px;width: 40px;background:#ccc;border-radius: 50%;line-height: 38px;text-align: center;" type="submit">
                                        
                                      </button>
                                         {% csrf_token %}
                                                </td></form>
                                                <td>
                                      <form action="{% url "cart:cart_add" product.id %}" method="post">                                      
                                      
                                             {% csrf_token %}
                                           </form>
                                      </td>
                                </tr>
                                {% endwith %}
                                    {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="continue__btn">
                                <a href="{% url 'cake:product_list' %}">Continue Shopping</a>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="continue__btn update__btn">

                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="cart__total">
                        <h6>Cart total</h6>
                        <ul>
                            <li>Subtotal <span>${{ cart.get_total_price }}</span></li>
                            <li>Total <span>$ {{ cart.get_total_price }}</span></li>
                        </ul>
                        
                        <a href="{% url 'orders:order_create' %}" class="primary-btn">Proceed to checkout</a>
              

                        
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Shopping Cart Section End -->
{% endblock %}

cart/templates/shoping-cart.html
{% extends "index.html" %}
   {% load static %}
{% block title %}
<title>Your shopping cart</title>
{% endblock %}
{% block content %}
    <!-- Breadcrumb Begin -->
    <div class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="breadcrumb__text">
                        <h2>Shopping cart</h2>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="breadcrumb__links">
                        <a href="./index.html">Home</a>
                        <span>Shopping cart</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <!-- Shopping Cart Section Begin -->
    <section class="shopping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="shopping__cart__table">
                        <table>
                            <thead>
                                <tr>
                                    <th>Product</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in cart %}
                                {% with product=item.product %}
                                <tr>
                                    <td class="product__cart__item">
                                        <div class="product__cart__item__pic">
                                            <img src="{{ product.image.url }}" alt="">
                                        </div>
                                        <div class="product__cart__item__text">
                                            <h6>{{product.name }}</h6>
                                            <h5>${{ item.price }}</h5>
                                        </div>
                                    </td>
                        <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                    <td class="quantity__item">
                                        <div class="quantity">
                                            <div class="pro-qty">
                                               <input name="quantity" id="id_quantity" type="text" value="1">
                                            </div>{% csrf_token %}
                                            {{ item.update_quantity_form.override }}
                                        </div>
                                    </td>
                                    </form>
                                    <td class="cart__price">$ {{ item.total_price }}</td>
                                    <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                                    <td class="cart__close">
                                        <input type="submit" name=""> <span class="icon_close"></span>{% csrf_token %}
                                                </td></form>
                                </tr>
                                {% endwith %}
                                    {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="continue__btn">
                                <a href="{% url 'cake:product_list' %}">Continue Shopping</a>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="continue__btn update__btn">
                                <a href="#"><i class="fa fa-spinner"></i> Update cart</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="cart__total">
                        <h6>Cart total</h6>
                        <ul>
                            <li>Subtotal <span>${{ cart.get_total_price }}</span></li>
                            <li>Total <span>$ {{ cart.get_total_price }}</span></li>
                        </ul>
                        <a href="{% url 'orders:order_create' %}" class="primary-btn">Proceed to checkout</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Shopping Cart Section End -->
{% endblock %}